pipeline {
    agent any

    tools {
        maven 'maven3'
    }

    environment {
        DOCKERHUB_REPO = "rayen122/student-management"
        IMAGE_NAME = "student-management"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Maven') {
            steps {
                dir('student-management') {
                    sh "mvn clean package -DskipTests"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('student-management') {
                    sh "docker build -t ${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Test Generated Image') {
            steps {
                echo "Testing if image was generated inside the container"
                sh """
                    docker run --rm student-management:latest \
                    ls -l /app
                """
            }
        }
    }

    post {
        success {
            echo "Build OK ✔"
        }
        failure {
            echo "Build FAILED ❌"
        }
    }
}
